import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

export interface StorageProvider {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<{ body: Buffer; contentType: string } | null>;
  delete(key: string): Promise<void>;
  /** Public URL for a stored object. */
  url(key: string): string;
  /** URL prefix such that `base + key` is the public URL (used by client-side previews). */
  publicBase(): string;
}

// Keys are generated by the platform (never taken from user input) and look
// like: stores/<storeId>/products/<uuid>.webp
const KEY_PATTERN = /^stores\/[0-9a-f-]{36}\/[a-z]+\/[0-9a-f-]{36}\.(webp|png|jpg)$/;
export const isValidKey = (key: string) => KEY_PATTERN.test(key);

const CONTENT_TYPES: Record<string, string> = { webp: "image/webp", png: "image/png", jpg: "image/jpeg" };

/**
 * Local-disk storage for development and single-server beta. Files are served
 * by the /media route. For multiple servers use an S3-compatible provider
 * (to be added with the hosting decision).
 */
class LocalStorage implements StorageProvider {
  constructor(private readonly root: string, private readonly base: string) {}

  private file(key: string) {
    if (!isValidKey(key)) throw new Error("Invalid storage key");
    return path.join(this.root, key);
  }

  async put(key: string, body: Buffer) {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
  }

  async get(key: string) {
    try {
      const body = await readFile(this.file(key));
      return { body, contentType: CONTENT_TYPES[key.split(".").pop()!] };
    } catch {
      return null;
    }
  }

  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }

  url(key: string) {
    return `${this.base}/media/${key}`;
  }

  publicBase() {
    return `${this.base}/media/`;
  }
}

let provider: StorageProvider | undefined;

export function getStorage(): StorageProvider {
  if (!provider) {
    const driver = process.env.STORAGE_DRIVER ?? "local";
    if (driver !== "local") throw new Error(`Unsupported STORAGE_DRIVER: ${driver}`);
    provider = new LocalStorage(
      path.resolve(/* turbopackIgnore: true */ process.env.STORAGE_DIR ?? ".data/uploads"),
      (process.env.APP_URL ?? "http://localhost:3000").replace(/\/$/, ""),
    );
  }
  return provider;
}

export function setStorage(p: StorageProvider | undefined) {
  provider = p;
}
